"""Utilities for NiCo niche covariation analysis."""

from .config import CovariationConfig, CovariationReportConfig, DEFAULT_RIDGE_ALPHAS
from .io import (
    load_feature_matrix,
    load_factors_info,
    planned_covariation_paths,
    read_covariation_manifest,
    read_covariation_state,
    resolve_ligand_receptor_db,
)
from .pipeline import (
    build_covariation_result,
    export_regression_table,
    load_covariation_result,
    run_covariation,
)
from .reports import (
    export_gene_correlations,
    export_ligand_receptor_summary,
    extract_top_genes,
    extract_top_genes_all_factors,
    generate_covariation_reports,
    plot_colocalized_factors,
    plot_factor_gene_heatmaps,
    plot_factor_umap,
    plot_feature_matrix,
    plot_ligand_receptor_interactions,
    plot_regression_covariations,
    plot_top_genes_all_factors,
    plot_top_genes_pair,
    require_nico_covariation_state,
    run_pathway_enrichment,
    write_report_manifest,
)
from .results import CovariationArtifactPaths, CovariationReportOutputs, CovariationResult
from .validation import (
    ValidationError,
    resolve_niche_context,
    validate_covariation_artifacts,
    validate_covariation_config,
    validate_covariation_inputs,
    validate_covariation_outputs,
    validate_double_modality_inputs,
    validate_single_modality_inputs,
)

__all__ = [
    "CovariationArtifactPaths",
    "CovariationConfig",
    "CovariationReportConfig",
    "CovariationReportOutputs",
    "CovariationResult",
    "DEFAULT_RIDGE_ALPHAS",
    "ValidationError",
    "build_covariation_result",
    "export_gene_correlations",
    "export_ligand_receptor_summary",
    "export_regression_table",
    "extract_top_genes",
    "extract_top_genes_all_factors",
    "generate_covariation_reports",
    "load_covariation_result",
    "load_feature_matrix",
    "load_factors_info",
    "planned_covariation_paths",
    "plot_colocalized_factors",
    "plot_factor_gene_heatmaps",
    "plot_factor_umap",
    "plot_feature_matrix",
    "plot_ligand_receptor_interactions",
    "plot_regression_covariations",
    "plot_top_genes_all_factors",
    "plot_top_genes_pair",
    "read_covariation_manifest",
    "read_covariation_state",
    "require_nico_covariation_state",
    "resolve_ligand_receptor_db",
    "resolve_niche_context",
    "run_covariation",
    "run_pathway_enrichment",
    "validate_covariation_artifacts",
    "validate_covariation_config",
    "validate_covariation_inputs",
    "validate_covariation_outputs",
    "validate_double_modality_inputs",
    "validate_single_modality_inputs",
    "write_report_manifest",
]
